server:
  port: 9000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: seamew
    password: ltr20001121
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true